// marching cubes build densities vertex shader

cbuffer MatrixBuffer : register(b0)
{
    matrix worldMatrix;
    matrix viewMatrix;
    matrix projectionMatrix;
};

struct VSInput
{
    float4 position     : POSITION;
    float2 tex          : TEXCOORD;
    uint   nInstanceID  : SV_InstanceID;   // generated by the vertex shader. each slice is an instance
};

struct VSOutput
{
    float4 position   : POSITION;
    float2 tex        : TEXCOORD;
    float4 position3D : TEXCOORD2;
    uint   nInstanceID  : SLICEINDEX;
};

VSOutput main(VSInput input)
{
    VSOutput output;

    input.position.w = 1.0f;

    // Calculate the position of the vertex against the world, view, and projection matrices.
    output.position = mul(input.position, worldMatrix);
    output.position = mul(output.position, viewMatrix);
    output.position = mul(output.position, projectionMatrix);

    // Store the texture coordinates for the pixel shader.
    output.tex = input.tex;

    float4 worldPos = float4(input.position.x, input.nInstanceID, input.position.z, 1);

    // world position of vertex (for point light)
    output.position3D = mul(worldPos, worldMatrix);

    //output.position3D = float4(input.tex.xy, input.nInstanceID * (1.0f / 10.0f), 1.0f);

    output.nInstanceID = input.nInstanceID;

    return output;
}